kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"openshift-sql-docker:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"openshift-sql-docker\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '2519624962'
  name: openshift-sql-docker
  uid: 06b0ba6f-b957-474a-b804-63658c4c6ba8
  creationTimestamp: '2025-08-14T13:40:13Z'
  generation: 2
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      time: '2025-08-14T13:40:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"openshift-sql-docker"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-08-14T13:40:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"openshift-sql-docker"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-08-14T13:41:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: yosefgu-dev
  labels:
    app: openshift-sql-docker
    app.kubernetes.io/component: openshift-sql-docker
    app.kubernetes.io/instance: openshift-sql-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: openshift-sql-docker
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: openshift-sql-docker
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: openshift-sql-docker
          image: 'image-registry.openshift-image-registry.svc:5000/yosefgu-dev/openshift-sql-docker@sha256:11b13b611493f816ad4e80c94aafd37cf11d115e962fc64020131e35ae569f9c'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-08-14T13:40:50Z'
      lastTransitionTime: '2025-08-14T13:40:13Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "openshift-sql-docker-b8fbf895b" has successfully progressed.
    - type: Available
      status: 'False'
      lastUpdateTime: '2025-08-14T13:41:31Z'
      lastTransitionTime: '2025-08-14T13:41:31Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
